services:
  - type: web
    name: my-like-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
      - key: DATABASE_URL
        fromDatabase:
          name: like-api-db
          property: connectionString
